### ISSUE TITLE
Consider linking to repository from crates.io

### ISSUE THREAD

**Issue by cpick** [Metaswitch/vault-client#5]
I believe this is the upstream repository for the [vault_client crate](https://crates.io/crates/vault_client), it that's the case would you consider linking to it from crates.io?  It took a small bit of detective work to find it.

**Comment by murrayrogers** [comment]
Yes!  @bjgill - are you able to handle?

**Comment by bossmc** [comment]
This is fixed in #2, but no new release has been pushed since that fix.  When a new release is cut, the link will appear.

**Comment by bjgill** [comment]
This is clearly causing problems. I'm therefore minded to publish a new version with no changes other than the addition of the link to the repo. I should be able to sort this out soon.

**Comment by bjgill** [comment]
Published.
